export const ActionTypes = {
    // product
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_FAVORITES:"SET_FAVORITES",
    // category
    SET_CATEGORIES: "SET_CATEGORIES",
    // user
    SET_USER: "SET_USER",
    // settings
    SET_SETTINGS: "SET_SETTINGS"
};